# Generated by Django 5.2.6 on 2025-10-22 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBAGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_game_id', models.CharField(max_length=20, unique=True, verbose_name='NBA Game ID')),
                ('season_id', models.CharField(max_length=20, verbose_name='Season ID')),
                ('game_date', models.DateField(verbose_name='Fecha del Partido')),
                ('season_type', models.CharField(max_length=20, verbose_name='Tipo de Temporada')),
                ('home_win', models.BooleanField(blank=True, null=True, verbose_name='Victoria Local')),
                ('home_points', models.IntegerField(blank=True, null=True, verbose_name='Puntos Local')),
                ('away_points', models.IntegerField(blank=True, null=True, verbose_name='Puntos Visitante')),
                ('total_points', models.IntegerField(blank=True, null=True, verbose_name='Puntos Totales')),
                ('home_minutes', models.IntegerField(blank=True, null=True, verbose_name='Minutos Local')),
                ('home_fgm', models.IntegerField(blank=True, null=True, verbose_name='Tiros Anotados Local')),
                ('home_fga', models.IntegerField(blank=True, null=True, verbose_name='Tiros Intentados Local')),
                ('home_fg_pct', models.FloatField(blank=True, null=True, verbose_name='% Tiros Local')),
                ('home_fg3m', models.IntegerField(blank=True, null=True, verbose_name='Triples Anotados Local')),
                ('home_fg3a', models.IntegerField(blank=True, null=True, verbose_name='Triples Intentados Local')),
                ('home_fg3_pct', models.FloatField(blank=True, null=True, verbose_name='% Triples Local')),
                ('home_ftm', models.IntegerField(blank=True, null=True, verbose_name='Tiros Libres Anotados Local')),
                ('home_fta', models.IntegerField(blank=True, null=True, verbose_name='Tiros Libres Intentados Local')),
                ('home_ft_pct', models.FloatField(blank=True, null=True, verbose_name='% Tiros Libres Local')),
                ('home_oreb', models.IntegerField(blank=True, null=True, verbose_name='Rebotes Ofensivos Local')),
                ('home_dreb', models.IntegerField(blank=True, null=True, verbose_name='Rebotes Defensivos Local')),
                ('home_reb', models.IntegerField(blank=True, null=True, verbose_name='Rebotes Totales Local')),
                ('home_ast', models.IntegerField(blank=True, null=True, verbose_name='Asistencias Local')),
                ('home_stl', models.IntegerField(blank=True, null=True, verbose_name='Robos Local')),
                ('home_blk', models.IntegerField(blank=True, null=True, verbose_name='Tapones Local')),
                ('home_tov', models.IntegerField(blank=True, null=True, verbose_name='Pérdidas Local')),
                ('home_pf', models.IntegerField(blank=True, null=True, verbose_name='Faltas Local')),
                ('home_plus_minus', models.IntegerField(blank=True, null=True, verbose_name='Plus/Minus Local')),
                ('away_minutes', models.IntegerField(blank=True, null=True, verbose_name='Minutos Visitante')),
                ('away_fgm', models.IntegerField(blank=True, null=True, verbose_name='Tiros Anotados Visitante')),
                ('away_fga', models.IntegerField(blank=True, null=True, verbose_name='Tiros Intentados Visitante')),
                ('away_fg_pct', models.FloatField(blank=True, null=True, verbose_name='% Tiros Visitante')),
                ('away_fg3m', models.IntegerField(blank=True, null=True, verbose_name='Triples Anotados Visitante')),
                ('away_fg3a', models.IntegerField(blank=True, null=True, verbose_name='Triples Intentados Visitante')),
                ('away_fg3_pct', models.FloatField(blank=True, null=True, verbose_name='% Triples Visitante')),
                ('away_ftm', models.IntegerField(blank=True, null=True, verbose_name='Tiros Libres Anotados Visitante')),
                ('away_fta', models.IntegerField(blank=True, null=True, verbose_name='Tiros Libres Intentados Visitante')),
                ('away_ft_pct', models.FloatField(blank=True, null=True, verbose_name='% Tiros Libres Visitante')),
                ('away_oreb', models.IntegerField(blank=True, null=True, verbose_name='Rebotes Ofensivos Visitante')),
                ('away_dreb', models.IntegerField(blank=True, null=True, verbose_name='Rebotes Defensivos Visitante')),
                ('away_reb', models.IntegerField(blank=True, null=True, verbose_name='Rebotes Totales Visitante')),
                ('away_ast', models.IntegerField(blank=True, null=True, verbose_name='Asistencias Visitante')),
                ('away_stl', models.IntegerField(blank=True, null=True, verbose_name='Robos Visitante')),
                ('away_blk', models.IntegerField(blank=True, null=True, verbose_name='Tapones Visitante')),
                ('away_tov', models.IntegerField(blank=True, null=True, verbose_name='Pérdidas Visitante')),
                ('away_pf', models.IntegerField(blank=True, null=True, verbose_name='Faltas Visitante')),
                ('away_plus_minus', models.IntegerField(blank=True, null=True, verbose_name='Plus/Minus Visitante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partido NBA',
                'verbose_name_plural': 'Partidos NBA',
                'ordering': ['-game_date', 'home_team'],
            },
        ),
        migrations.CreateModel(
            name='NBAPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_id', models.CharField(max_length=20, unique=True, verbose_name='NBA ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jugador NBA',
                'verbose_name_plural': 'Jugadores NBA',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='NBATeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_id', models.CharField(max_length=20, unique=True, verbose_name='NBA ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('nickname', models.CharField(max_length=50, verbose_name='Apodo')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('year_founded', models.IntegerField(verbose_name='Año de Fundación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo NBA',
                'verbose_name_plural': 'Equipos NBA',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='NBAPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_total_points', models.FloatField(verbose_name='Puntos Totales Predichos')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Confianza (%)')),
                ('over_220_probability', models.FloatField(blank=True, null=True, verbose_name='Probabilidad Over 220')),
                ('over_230_probability', models.FloatField(blank=True, null=True, verbose_name='Probabilidad Over 230')),
                ('over_240_probability', models.FloatField(blank=True, null=True, verbose_name='Probabilidad Over 240')),
                ('model_name', models.CharField(max_length=100, verbose_name='Nombre del Modelo')),
                ('model_version', models.CharField(max_length=20, verbose_name='Versión del Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='basketball_data.nbagame', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Predicción NBA',
                'verbose_name_plural': 'Predicciones NBA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='nbagame',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='basketball_data.nbateam', verbose_name='Equipo Visitante'),
        ),
        migrations.AddField(
            model_name='nbagame',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='basketball_data.nbateam', verbose_name='Equipo Local'),
        ),
        migrations.AlterUniqueTogether(
            name='nbagame',
            unique_together={('nba_game_id',)},
        ),
    ]
