# Generated by Django 5.2.6 on 2025-09-14 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Casa de Apuestas',
                'verbose_name_plural': 'Casas de Apuestas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, unique=True)),
                ('home_team', models.CharField(max_length=200)),
                ('away_team', models.CharField(max_length=200)),
                ('commence_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['commence_time'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('has_outrights', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AverageOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_home_odds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('avg_away_odds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('avg_draw_odds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bookmaker_count', models.IntegerField()),
                ('standard_deviation', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='average_odds', to='odds.match')),
            ],
            options={
                'verbose_name': 'Cuota Promedio',
                'verbose_name_plural': 'Cuotas Promedio',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odds.sport'),
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_odds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('away_odds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('draw_odds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('odds_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odds.bookmaker')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='odds.match')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-odds_timestamp'],
                'unique_together': {('match', 'bookmaker', 'odds_timestamp')},
            },
        ),
    ]
