# Generated by Django 5.2.6 on 2025-09-14 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetfairAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('available_to_bet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exposure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retained_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exposure_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points_balance', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('sandbox', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta Betfair',
                'verbose_name_plural': 'Cuentas Betfair',
            },
        ),
        migrations.CreateModel(
            name='BetfairEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('market_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evento Betfair',
                'verbose_name_plural': 'Tipos de Eventos Betfair',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BetfairEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('open_date', models.DateTimeField()),
                ('market_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.betfaireventtype')),
            ],
            options={
                'verbose_name': 'Evento Betfair',
                'verbose_name_plural': 'Eventos Betfair',
                'ordering': ['open_date'],
            },
        ),
        migrations.CreateModel(
            name='BetfairMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=50, unique=True)),
                ('market_name', models.CharField(max_length=200)),
                ('market_start_time', models.DateTimeField()),
                ('market_type', models.CharField(default='MATCH_ODDS', max_length=50)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactivo'), ('OPEN', 'Abierto'), ('SUSPENDED', 'Suspendido'), ('CLOSED', 'Cerrado')], default='INACTIVE', max_length=20)),
                ('total_matched', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='betfair.betfairevent')),
            ],
            options={
                'verbose_name': 'Mercado Betfair',
                'verbose_name_plural': 'Mercados Betfair',
                'ordering': ['market_start_time'],
            },
        ),
        migrations.CreateModel(
            name='BetfairRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_id', models.BigIntegerField()),
                ('runner_name', models.CharField(max_length=200)),
                ('sort_priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('WINNER', 'Ganador'), ('LOSER', 'Perdedor'), ('REMOVED', 'Eliminado')], default='ACTIVE', max_length=20)),
                ('last_price_traded', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_matched', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available_to_back', models.JSONField(blank=True, default=dict)),
                ('available_to_lay', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='betfair.betfairmarket')),
            ],
            options={
                'verbose_name': 'Corredor Betfair',
                'verbose_name_plural': 'Corredores Betfair',
                'ordering': ['sort_priority'],
                'unique_together': {('market', 'selection_id')},
            },
        ),
        migrations.CreateModel(
            name='BetfairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('side', models.CharField(choices=[('BACK', 'A favor'), ('LAY', 'En contra')], max_length=10)),
                ('order_type', models.CharField(choices=[('LIMIT', 'Límite'), ('MARKET_ON_CLOSE', 'Mercado al cierre'), ('LIMIT_ON_CLOSE', 'Límite al cierre')], max_length=20)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('EXECUTABLE', 'Ejecutable'), ('EXECUTION_COMPLETE', 'Ejecución completa'), ('CANCELLED', 'Cancelada'), ('FAILED', 'Fallida')], default='PENDING', max_length=30)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.betfairmarket')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.betfairrunner')),
            ],
            options={
                'verbose_name': 'Orden Betfair',
                'verbose_name_plural': 'Órdenes Betfair',
                'ordering': ['-placed_at'],
            },
        ),
    ]
