# Generated by Django 5.2.6 on 2025-09-23 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetfairTickSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_back', models.JSONField(blank=True, default=list)),
                ('best_lay', models.JSONField(blank=True, default=list)),
                ('last_price_traded', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_matched', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_snapshots', to='betfair.betfairmarket')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_snapshots', to='betfair.betfairrunner')),
            ],
            options={
                'verbose_name': 'Tick Snapshot Betfair',
                'verbose_name_plural': 'Tick Snapshots Betfair',
                'indexes': [models.Index(fields=['market', 'captured_at'], name='betfair_bet_market__e5fb94_idx'), models.Index(fields=['runner', 'captured_at'], name='betfair_bet_runner__c50169_idx')],
            },
        ),
    ]
