# Generated by Django 5.2.6 on 2025-09-14 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betfair', '0001_initial'),
        ('odds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_edge', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('min_confidence', models.DecimalField(decimal_places=2, default=0.6, max_digits=3)),
                ('min_stake', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_stake', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('max_daily_bets', models.IntegerField(default=10)),
                ('allowed_sports', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estrategia de Apuestas',
                'verbose_name_plural': 'Estrategias de Apuestas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('STRING', 'Texto'), ('INTEGER', 'Entero'), ('FLOAT', 'Decimal'), ('BOOLEAN', 'Booleano'), ('JSON', 'JSON')], default='STRING', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Bot',
                'verbose_name_plural': 'Configuraciones del Bot',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('home', 'Local'), ('away', 'Visitante'), ('draw', 'Empate')], max_length=10)),
                ('odds_api_odds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('betfair_odds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('edge', models.DecimalField(decimal_places=5, max_digits=8)),
                ('recommended_stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acted_upon', models.BooleanField(default=False)),
                ('bet_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='betfair.betfairorder')),
                ('betfair_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.betfairmarket')),
                ('betfair_runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betfair.betfairrunner')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odds.match')),
            ],
            options={
                'verbose_name': 'Oportunidad de Arbitraje',
                'verbose_name_plural': 'Oportunidades de Arbitraje',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('STARTING', 'Iniciando'), ('RUNNING', 'Ejecutándose'), ('PAUSED', 'Pausado'), ('STOPPED', 'Detenido'), ('ERROR', 'Error')], default='STARTING', max_length=20)),
                ('cycles_executed', models.IntegerField(default=0)),
                ('opportunities_found', models.IntegerField(default=0)),
                ('bets_placed', models.IntegerField(default=0)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_cycle_at', models.DateTimeField(blank=True, null=True)),
                ('execution_interval', models.IntegerField(default=10)),
                ('sandbox_mode', models.BooleanField(default=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.bettingstrategy')),
            ],
            options={
                'verbose_name': 'Sesión del Bot',
                'verbose_name_plural': 'Sesiones del Bot',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BotCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField()),
                ('matches_analyzed', models.IntegerField(default=0)),
                ('opportunities_found', models.IntegerField(default=0)),
                ('bets_placed', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('duration_seconds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('success_status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('PARTIAL', 'Parcial'), ('FAILED', 'Fallido')], default='SUCCESS', max_length=20)),
                ('logs', models.TextField(blank=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='betting.botsession')),
            ],
            options={
                'verbose_name': 'Ciclo del Bot',
                'verbose_name_plural': 'Ciclos del Bot',
                'ordering': ['-started_at'],
                'unique_together': {('session', 'cycle_number')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('SUCCESS', 'Éxito')], default='INFO', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betting.botcycle')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betting.botsession')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
