# Generated by Django 5.2.6 on 2025-09-23 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('initial_bankroll', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_bankroll', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roi', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('hit_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('total_bets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.bettingstrategy')),
            ],
            options={
                'verbose_name': 'Ejecución de Backtest',
                'verbose_name_plural': 'Ejecuciones de Backtest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=50)),
                ('selection_id', models.BigIntegerField()),
                ('side', models.CharField(choices=[('BACK', 'BACK'), ('LAY', 'LAY')], max_length=10)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('decided_at', models.DateTimeField()),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betting.backtestrun')),
            ],
            options={
                'verbose_name': 'Apuesta Backtest',
                'verbose_name_plural': 'Apuestas Backtest',
            },
        ),
        migrations.CreateModel(
            name='StrategyParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_sets', to='betting.bettingstrategy')),
            ],
            options={
                'verbose_name': 'Parámetros de Estrategia',
                'verbose_name_plural': 'Parámetros de Estrategia',
                'unique_together': {('strategy', 'name')},
            },
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='parameter_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.strategyparameterset'),
        ),
    ]
