# Generated by Django 5.2.6 on 2025-09-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ahch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Asian Handicap Corners'),
        ),
        migrations.AddField(
            model_name='match',
            name='avgc_over_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Avg Corners Over 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='avgc_under_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Avg Corners Under 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='avgca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Avg Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='avgcaha',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Avg AH Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='avgcahh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Avg AH Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='avgcd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Avg Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='avgch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Avg Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='b365c_over_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Bet365 Corners Over 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='b365c_under_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Bet365 Corners Under 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='b365ca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Bet365 Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='b365caha',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Bet365 AH Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='b365cahh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Bet365 AH Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='b365cd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Bet365 Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='b365ch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Bet365 Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfda',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFD Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfdca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFD Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfdcd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFD Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfdch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFD Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfdd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFD Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfdh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFD Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfe_over_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE Over 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfe_under_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE Under 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfea',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfeaha',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE AH Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfeahh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE AH Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfec_over_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE Corners Over 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfec_under_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE Corners Under 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfeca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfecaha',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE AH Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfecahh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE AH Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfecd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfech',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='bfeh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BFE Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bmgma',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BMGM Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bmgmca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BMGM Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bmgmcd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BMGM Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='bmgmch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BMGM Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bmgmd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BMGM Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='bmgmh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BMGM Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bva',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BV Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bvca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BV Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bvcd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BV Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='bvch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BV Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bvd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BV Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='bvh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BV Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='bwca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BW Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='bwcd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BW Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='bwch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='BW Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='cla',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='CL Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='clca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='CL Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='clcd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='CL Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='clch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='CL Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='cld',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='CL Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='clh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='CL Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='lba',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='LB Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='lbca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='LB Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='lbcd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='LB Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='lbch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='LB Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='lbd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='LB Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='lbh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='LB Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='maxc_over_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Max Corners Over 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='maxc_under_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Max Corners Under 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='maxca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Max Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='maxcaha',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Max AH Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='maxcahh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Max AH Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='maxcd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Max Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='maxch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Max Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='pc_over_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='PS Corners Over 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='pc_under_25',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='PS Corners Under 2.5'),
        ),
        migrations.AddField(
            model_name='match',
            name='pcaha',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='PS AH Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='pcahh',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='PS AH Corners Home'),
        ),
        migrations.AddField(
            model_name='match',
            name='psca',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='PS Corners Away'),
        ),
        migrations.AddField(
            model_name='match',
            name='pscd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='PS Corners Draw'),
        ),
        migrations.AddField(
            model_name='match',
            name='psch',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='PS Corners Home'),
        ),
    ]
