# Generated by Django 5.2.6 on 2025-09-23 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0002_match_ahch_match_avgc_over_25_match_avgc_under_25_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='football_data.excelfile'),
        ),
    ]
