# Generated by Django 5.2.6 on 2025-09-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_data', '0003_match_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='both_teams_score',
            field=models.BooleanField(blank=True, null=True, verbose_name='Both Teams Score'),
        ),
        migrations.AddField(
            model_name='match',
            name='corners_1h',
            field=models.IntegerField(blank=True, null=True, verbose_name='Corners 1st Half'),
        ),
        migrations.AddField(
            model_name='match',
            name='corners_2h',
            field=models.IntegerField(blank=True, null=True, verbose_name='Corners 2nd Half'),
        ),
        migrations.AddField(
            model_name='match',
            name='corners_away',
            field=models.IntegerField(blank=True, null=True, verbose_name='Away Corners'),
        ),
        migrations.AddField(
            model_name='match',
            name='corners_home',
            field=models.IntegerField(blank=True, null=True, verbose_name='Home Corners'),
        ),
        migrations.AddField(
            model_name='match',
            name='corners_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Corners'),
        ),
    ]
