"""
Django settings for betting_bot project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-05hl%jnp2o6j)8)zo=u8eu9_zkk7yd8h7&w^x6xix%@y*owsu+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Aplicaciones del proyecto
    'cuentas',
    'odds',
    'betfair',
    'betting',
    'football_data',
    'ai_predictions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'betting_bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'betting_bot' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'betting_bot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Directorios donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de autenticación
AUTH_USER_MODEL = 'cuentas.Usuario'
LOGIN_URL = '/cuentas/login/'
LOGIN_REDIRECT_URL = '/cuentas/dashboard/'
LOGOUT_REDIRECT_URL = '/cuentas/login/'


# Configuración del bot de apuestas
ODDS_API_KEY = os.getenv('ODDS_API_KEY', '9c2c101074ae4a4c3ec9b01a4d38cb6a')
ODDS_API_BASE_URL = 'https://api.the-odds-api.com/v4'

# Configuración de Betfair
BETFAIR_APP_KEY = os.getenv('BETFAIR_APP_KEY', 'your_betfair_app_key_here')
BETFAIR_USERNAME = os.getenv('BETFAIR_USERNAME', 'your_betfair_username_here')
BETFAIR_PASSWORD = os.getenv('BETFAIR_PASSWORD', 'your_betfair_password_here')
BETFAIR_SANDBOX = os.getenv('BETFAIR_SANDBOX', 'True').lower() == 'true'

# Configuración del bot
SPORT_KEY = os.getenv('SPORT_KEY', 'soccer_epl')
REGIONS = os.getenv('REGIONS', 'uk,us,eu')
MARKETS = os.getenv('MARKETS', 'h2h')
ODDS_FORMAT = os.getenv('ODDS_FORMAT', 'decimal')

# Configuración de apuestas
MIN_STAKE = float(os.getenv('MIN_STAKE', '1.0'))
MAX_STAKE = float(os.getenv('MAX_STAKE', '10.0'))
MIN_EDGE = float(os.getenv('MIN_EDGE', '0.05'))

# Intervalo de ejecución (segundos)
EXECUTION_INTERVAL = int(os.getenv('EXECUTION_INTERVAL', '10'))

# Configuración de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'betting_bot.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'odds': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'betfair': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'betting': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
